<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

    <SatelliteResourceLanguages>ja-JP</SatelliteResourceLanguages>
    <NeutralLanguage>ja-JP</NeutralLanguage>
    <Copyright>Copyright 2026 sharkin910@gmail.com</Copyright>
    <Title>File Grep Tool</Title>
    <AssemblyTitle>$(Title)</AssemblyTitle>
    <Version>1.0.1.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <ProductVersion>$(Version)</ProductVersion>
    <AssemblyFileVersion>$(Version)</AssemblyFileVersion>
    <FileVersion>$(Version)</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="FormMain.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FormMain.Designer.cs">
      <DependentUpon>FormMain.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
      <Using Include="System.Collections.Generic" />
      <Using Include="System.IO" />
    <Using Include="System.Linq" />
  </ItemGroup>

</Project>
